version: '2'

services:
  consul:
    image: progrium/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: [-server, -bootstrap, -ui-dir, /ui]
  registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # 192.168.99.100 is the host ip
    command: [-ip, 192.168.99.100, -retry-attempts, "-1", "consulkv://192.168.99.100:8500/elb"]
    depends_on:
      - consul
  webapp1:
    image: runseb/hostname
    ports:
      - 5001:5000
    depends_on:
      - registrator
  webapp2:
    image: runseb/hostname
    ports:
      - 5002:5000
    depends_on:
      - registrator
  # webapp3:
  #   image: runseb/hostname
  #   ports:
  #     - 5003:5000
  #   depends_on:
  #     - registrator
  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    container_name: elb
    ports:
      - "80:80"